#service
apiVersion: v1
kind: Service
metadata:
  name: devopsproj
  labels:
    app: devopsproj
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: devopsproj
  type: ClusterIP
